language: node_js
script: npm test
sudo: required
addons:
  hosts:
    - local-sso.panel.my-webapp.com
    - local-intranet.panel.my-webapp.com
after_success:
  - cat bin/coverage/lcov.info | ./node_modules/.bin/coveralls
